### PR TITLE
Feature: enable multiple snapshots

### PR DESCRIPTION
**Pull request by adamsilverstein**
Addresses https://github.com/10up/wpacceptance/issues/3.

### CODE REVIEW

**Comment by adamsilverstein** [comment]
This worked in my initial testing. Going to test with Distributor.

**Comment by tlovett1** [comment]
@adamsilverstein looking through the docs and I'm a bit confused on the logic. If I run the `run` command with no arguments and `snapshot_id` and `snapshots` are both present in `wpassure.json` what happens?

**Comment by adamsilverstein** [comment]
> looking through the docs and I'm a bit confused on the logic.

I'll work on improving the docs to clear this up. Open to ideas about HOW this should work, my goal is to have it backwards compatible with the existing system, eg adding a snapshots array is completely optional.

> If I run the run command with no arguments and `snapshot_id` and `snapshots` are both present in wpassure.json what happens?

Here is what I propose:

* When `snapshots` is **not** defined: no change to current behavior. 
* When `snapshots` is defined: the `run` command with no arguments _runs the tests against all of the snapshots in the array,  ignoring the snapshot_id_
* Running with tests with `--save --local` follows the current behavior: testing, then pushing the local snaphot up as a new image, and putting this new id in `snapshot_id`.
* Although the developer could add the new id to the snapshots array manually, we can also enable a new command `--add="[Snapshot Name]"`that does this automatically, eg. something like: `./vendor/bin/wpacceptance run --local --save --add="WordPress 5.1 plus Gutenberg 5.2"`. this would run the tests, save the snapshot, set the snapshot_id **and add a new entry in the `snapshots` array.**

@tlovett1 Any comments questions?

**Comment by adamsilverstein** [comment]
* Tested in https://github.com/10up/distributor/pull/342 verified this runs tests against each machine in the array.

**Pull request merged**
